#!/bin/bash

#searches for bills passed by the house but not the senate going back to the 105th congress (1997)  NOTE - toggle for pre and post 113th congress, because pro-publica API db changes.

#raw curl in case you need it for testing purposes "curl -H 'X-Api-Key: REPLACEWITHYOURAPIKEY' https://api.propublica.org/congress/v1/113/house/bills/passed.json"

#usage: ./house-bills.sh

#backup old file
cat house-bills.txt > house-bills-old.txt
> house-bills.txt

#print column names to screen, then to output file
echo "congress | bill_id | title | sponsor_name | sponsor_state | sponsor_party | date_introduced | house_passed | senate_passed | enacted | last_action_date | last_action | url"
echo "congress|bill_id|title|sponsor_name|sponsor_state|sponsor_party|date_introduced|house_passed|senate_passed|enacted|last_action_date|last_action|url" >> house-bills.txt

#iterate over number of congresses (105th congress is as far back as proPublica has detailed records)
#for i in {105..112} #pre-113th congress, attributes are less, so use introduced.json
for i in {114..114} #post 113th congress, use active
do

#url_base="https://api.propublica.org/congress/v1/$i/house/bills/introduced.json" #pre-113th version
url_base="https://api.propublica.org/congress/v1/$i/house/bills/passed.json" #post-113th version

page_first=$(curl -H 'X-Api-Key: INSERTYOURAPIKEYHERE' $url_base ) #Replace with your own API key from ProPublica

#strips spaces
page_stripped_first="$(echo -e "${page_first}" | sed -e ':a;N;$!ba;s/\n//g' -e 's/\s//g')"

#replaces spaces with _ (for titles)
title_list_first="$(echo -e "${page_first}" | sed -e 's/\s/_/g')"

#bill1
bill1raw_first=$(echo $page_stripped_first | grep -oP "bill_id.*?(?=\}\,\{)")
bill1_first=$(echo $bill1raw_first | awk '{print $1}')
id1raw_first=$(echo $page_stripped_first | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id1_first=$(echo $id1raw_first | awk '{print $1}')
title1raw_first=$(echo $title_list_first | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title1_first=$(echo $title1raw_first | awk '{print $1}')
sponsor1raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor1_first=$(echo $sponsor1raw_first | awk '{print $1}')
sponsorst1raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst1_first=$(echo $sponsorst1raw_first | awk '{print $1}')
sponsorpar1raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar1_first=$(echo $sponsorpar1raw_first | awk '{print $1}')
date1raw_first=$(echo $page_stripped_first | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date1_first=$(echo $date1raw_first | awk '{print $1}')
house1raw_first=$(echo $page_stripped_first | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house1_first=$(echo $house1raw_first | awk '{print $1}')
senate1raw_first=$(echo $page_stripped_first | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate1_first=$(echo $senate1raw_first | awk '{print $1}')
enacted1raw_first=$(echo $page_stripped_first | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted1_first=$(echo $enacted1raw_first | awk '{print $1}')
sponsor1raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor1_first=$(echo $sponsor1raw_first | awk '{print $1}')
last_action_date1raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date1_first=$(echo $last_action_date1raw_first | awk '{print $1}')
last_action1raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action1_first=$(echo $last_action1raw_first | awk '{print $1}')
url1raw_first=$(echo $page_stripped_first | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url1_first=$(echo $url1raw_first | awk '{print $1}')

echo "$i | $id1_first | $title1_first | $sponsor1_first | $sponsorst1_first | $sponsorpar1_first | $date1_first | $house1_first | $senate1_first | $enacted1_first | $last_action_date1first | $last_action1first | $url1_first"
echo "$i|$id1_first|$title1_first|$sponsor1_first|$sponsorst1_first|$sponsorpar1_first|$date1_first|$house1_first|$senate1_first|$enacted1_first|$last_action_date1_first|$last_action_first|$url1_first" >> house-bills.txt

#bill2
bill2raw_first=$(echo $page_stripped_first | grep -oP "bill_id.*?(?=\}\,\{)")
bill2_first=$(echo $bill2raw_first | awk '{print $2}')
id2raw_first=$(echo $page_stripped_first | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id2_first=$(echo $id2raw_first | awk '{print $2}')
title2raw_first=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title2_first=$(echo $title2raw_first | awk '{print $2}')
sponsor2raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor2_first=$(echo $sponsor2raw_first | awk '{print $2}')
sponsorst2raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst2_first=$(echo $sponsorst2raw_first | awk '{print $2}')
sponsorpar2raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar2_first=$(echo $sponsorpar2raw_first | awk '{print $2}')
date2raw_first=$(echo $page_stripped_first | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date2_first=$(echo $date2raw_first | awk '{print $2}')
house2raw_first=$(echo $page_stripped_first | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house2_first=$(echo $house2raw_first | awk '{print $2}')
senate2raw_first=$(echo $page_stripped_first | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate2_first=$(echo $senate2raw_first | awk '{print $2}')
enacted2raw_first=$(echo $page_stripped_first | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted2_first=$(echo $enacted2raw_first | awk '{print $2}')
sponsor2raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor2_first=$(echo $sponsor2raw_first | awk '{print $2}')
last_action_date2raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date2_first=$(echo $last_action_date2raw_first | awk '{print $2}')
last_action2raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action2_first=$(echo $last_action2raw_first | awk '{print $2}')
url2raw_first=$(echo $page_stripped_first | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url2_first=$(echo $url2raw_first | awk '{print $2}')

echo "$i | $id2_first | $title2_first | $sponsor2_first | $sponsorst2_first | $sponsorpar2_first | $date2_first | $house2_first | $senate2_first | $enacted2_first | $last_action_date2_first | $last_action2_first | $url2_first"
echo "$i|$id2_first|$title2_first|$sponsor2_first|$sponsorst2_first|$sponsorpar2_first|$date2_first|$house2_first|$senate2_first|$enacted2_first|$last_action_date2_first|$last_action2_first|$url2_first" >> house-bills.txt

#bill3
bill3raw_first=$(echo $page_stripped_first | grep -oP "bill_id.*?(?=\}\,\{)")
bill3_first=$(echo $bill3raw_first | awk '{print $3}')
id3raw_first=$(echo $page_stripped_first | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id3_first=$(echo $id3raw_first | awk '{print $3}')
title3raw_first=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title3_first=$(echo $title3raw_first | awk '{print $3}')
sponsor3raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor3_first=$(echo $sponsor3raw_first | awk '{print $3}')
sponsorst3raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst3_first=$(echo $sponsorst3raw_first | awk '{print $3}')
sponsorpar3raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar3_first=$(echo $sponsorpar3raw_first | awk '{print $3}')
date3raw_first=$(echo $page_stripped_first | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date3_first=$(echo $date3raw_first | awk '{print $3}')
house3raw_first=$(echo $page_stripped_first | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house3_first=$(echo $house3raw_first | awk '{print $3}')
senate3raw_first=$(echo $page_stripped_first | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate3_first=$(echo $senate3raw_first | awk '{print $3}')
enacted3raw_first=$(echo $page_stripped_first | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted3_first=$(echo $enacted3raw_first | awk '{print $3}')
sponsor3raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor3_first=$(echo $sponsor3raw_first | awk '{print $3}')
last_action_date3raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date3_first=$(echo $last_action_date3raw_first | awk '{print $3}')
last_action3raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action3_first=$(echo $last_action3raw_first | awk '{print $3}')
url3raw_first=$(echo $page_stripped_first | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url3_first=$(echo $url3raw_first | awk '{print $3}')

echo "$i | $id3_first | $title3_first | $sponsor3_first | $sponsorst3_first | $sponsorpar3_first | $date3_first | $house3_first | $senate3_first | $enacted3_first | $last_action_date3_first | $last_action3_first | $url3_first"
echo "$i|$id3_first|$title3_first|$sponsor3_first|$sponsorst3_first|$sponsorpar3_first|$date3_first|$house3_first|$senate3_first|$enacted3_first|$last_action_date3_first|$last_action3_first|$url3_first" >> house-bills.txt

#bill4
bill4raw_first=$(echo $page_stripped_first | grep -oP "bill_id.*?(?=\}\,\{)")
bill4_first=$(echo $bill4raw_first | awk '{print $4}')
id4raw_first=$(echo $page_stripped_first | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id4_first=$(echo $id4raw_first | awk '{print $4}')
title4raw_first=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title4_first=$(echo $title4raw_first | awk '{print $4}')
sponsor4raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor4_first=$(echo $sponsor4raw_first | awk '{print $4}')
sponsorst4raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst4_first=$(echo $sponsorst4raw_first | awk '{print $4}')
sponsorpar4raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar4_first=$(echo $sponsorpar4raw_first | awk '{print $4}')
date4raw_first=$(echo $page_stripped_first | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date4_first=$(echo $date4raw_first | awk '{print $4}')
house4raw_first=$(echo $page_stripped_first | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house4_first=$(echo $house4raw_first | awk '{print $4}')
senate4raw_first=$(echo $page_stripped_first | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate4_first=$(echo $senate4raw_first | awk '{print $4}')
enacted4raw_first=$(echo $page_stripped_first | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted4_first=$(echo $enacted4raw_first | awk '{print $4}')
sponsor4raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor4_first=$(echo $sponsor4raw_first | awk '{print $4}')
last_action_date4raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date4_first=$(echo $last_action_date4raw_first | awk '{print $4}')
last_action4raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action4_first=$(echo $last_action4raw_first | awk '{print $4}')
url4raw_first=$(echo $page_stripped_first | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url4_first=$(echo $url4raw_first | awk '{print $4}')

echo "$i | $id4_first | $title4_first | $sponsor4_first | $sponsorst4_first | $sponsorpar4_first | $date4_first | $house4_first | $senate4_first | $enacted4_first | $last_action_date4_first | $last_action4_first | $url4_first"
echo "$i|$id4_first|$title4_first|$sponsor4_first|$sponsorst4_first|$sponsorpar4_first|$date4_first|$house4_first|$senate4_first|$enacted4_first|$last_action_date4_first|$last_action4_first|$url4_first" >> house-bills.txt

#bill5
bill5raw_first=$(echo $page_stripped_first | grep -oP "bill_id.*?(?=\}\,\{)")
bill5_first=$(echo $bill5raw_first | awk '{print $5}')
id5raw_first=$(echo $page_stripped_first | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id5_first=$(echo $id5raw_first | awk '{print $5}')
title5raw_first=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title5_first=$(echo $title5raw_first | awk '{print $5}')
sponsor5raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor5_first=$(echo $sponsor5raw_first | awk '{print $5}')
sponsorst5raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst5_first=$(echo $sponsorst5raw_first | awk '{print $5}')
sponsorpar5raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar5_first=$(echo $sponsorpar5raw_first | awk '{print $5}')
date5raw_first=$(echo $page_stripped_first | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date5_first=$(echo $date5raw_first | awk '{print $5}')
house5raw_first=$(echo $page_stripped_first | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house5_first=$(echo $house5raw_first | awk '{print $5}')
senate5raw_first=$(echo $page_stripped_first | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate5_first=$(echo $senate5raw_first | awk '{print $5}')
enacted5raw_first=$(echo $page_stripped_first | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted5_first=$(echo $enacted5raw_first | awk '{print $5}')
sponsor5raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor5_first=$(echo $sponsor5raw_first | awk '{print $5}')
last_action_date5raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date5_first=$(echo $last_action_date5raw_first | awk '{print $5}')
last_action5raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action5_first=$(echo $last_action5raw_first | awk '{print $5}')
url5raw_first=$(echo $page_stripped_first | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url5_first=$(echo $url5raw_first | awk '{print $5}')

echo "$i | $id5_first | $title5_first | $sponsor5_first | $sponsorst5_first | $sponsorpar5_first | $date5_first | $house5_first | $senate5_first | $enacted5_first | $last_action_date5_first | $last_action5_first | $url5_first"
echo "$i|$id5_first|$title5_first|$sponsor5_first|$sponsorst5_first|$sponsorpar5_first|$date5_first|$house5_first|$senate5_first|$enacted5_first|$last_action_date5_first|$last_action5_first|$url5_first" >> house-bills.txt

#bill6
bill6raw_first=$(echo $page_stripped_first | grep -oP "bill_id.*?(?=\}\,\{)")
bill6_first=$(echo $bill6raw_first | awk '{print $6}')
id6raw_first=$(echo $page_stripped_first | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id6_first=$(echo $id6raw_first | awk '{print $6}')
title6raw_first=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title6_first=$(echo $title6raw_first | awk '{print $6}')
sponsor6raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor6_first=$(echo $sponsor6raw_first | awk '{print $6}')
sponsorst6raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst6_first=$(echo $sponsorst6raw_first | awk '{print $6}')
sponsorpar6raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar6_first=$(echo $sponsorpar6raw_first | awk '{print $6}')
date6raw_first=$(echo $page_stripped_first | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date6_first=$(echo $date6raw_first | awk '{print $6}')
house6raw_first=$(echo $page_stripped_first | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house6_first=$(echo $house6raw_first | awk '{print $6}')
senate6raw_first=$(echo $page_stripped_first | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate6_first=$(echo $senate6raw_first | awk '{print $6}')
enacted6raw_first=$(echo $page_stripped_first | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted6_first=$(echo $enacted6raw_first | awk '{print $6}')
sponsor6raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor6_first=$(echo $sponsor6raw_first | awk '{print $6}')
last_action_date6raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date6_first=$(echo $last_action_date6raw_first | awk '{print $6}')
last_action6raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action6_first=$(echo $last_action6raw_first | awk '{print $6}')
url6raw_first=$(echo $page_stripped_first | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url6_first=$(echo $url6raw_first | awk '{print $6}')

echo "$i | $id6_first | $title6_first | $sponsor6_first | $sponsorst6_first | $sponsorpar6_first | $date6_first | $house6_first | $senate6_first | $enacted6_first | $last_action_date6_first | $last_action6_first | $url6_first"
echo "$i|$id6_first|$title6_first|$sponsor6_first|$sponsorst6_first|$sponsorpar6_first|$date6_first|$house6_first|$senate6_first|$enacted6_first|$last_action_date6_first|$last_action6_first|$url6_first" >> house-bills.txt

#bill7
bill7raw_first=$(echo $page_stripped_first | grep -oP "bill_id.*?(?=\}\,\{)")
bill7_first=$(echo $bill7raw_first | awk '{print $7}')
id7raw_first=$(echo $page_stripped_first | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id7_first=$(echo $id7raw_first | awk '{print $7}')
title7raw_first=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title7_first=$(echo $title7raw_first | awk '{print $7}')
sponsor7raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor7_first=$(echo $sponsor7raw_first | awk '{print $7}')
sponsorst7raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst7_first=$(echo $sponsorst7raw_first | awk '{print $7}')
sponsorpar7raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar7_first=$(echo $sponsorpar7raw_first | awk '{print $7}')
date7raw_first=$(echo $page_stripped_first | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date7_first=$(echo $date7raw_first | awk '{print $7}')
house7raw_first=$(echo $page_stripped_first | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house7_first=$(echo $house7raw_first | awk '{print $7}')
senate7raw_first=$(echo $page_stripped_first | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate7_first=$(echo $senate7raw_first | awk '{print $7}')
enacted7raw_first=$(echo $page_stripped_first | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted7_first=$(echo $enacted7raw_first | awk '{print $7}')
sponsor7raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor7_first=$(echo $sponsor7raw_first | awk '{print $7}')
last_action_date7raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date7_first=$(echo $last_action_date7raw_first | awk '{print $7}')
last_action7raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action7_first=$(echo $last_action7raw_first | awk '{print $7}')
url7raw_first=$(echo $page_stripped_first | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url7_first=$(echo $url7raw_first | awk '{print $7}')

echo "$i | $id7_first | $title7_first | $sponsor7_first | $sponsorst7_first | $sponsorpar7_first | $date7_first | $house7_first | $senate7_first | $enacted7_first | $last_action_date7_first | $last_action7_first | $url7_first"
echo "$i|$id7_first|$title7_first|$sponsor7_first|$sponsorst7_first|$sponsorpar7_first|$date7_first|$house7_first|$senate7_first|$enacted7_first|$last_action_date7_first|$last_action7_first|$url7_first" >> house-bills.txt

#bill8
bill8raw_first=$(echo $page_stripped_first | grep -oP "bill_id.*?(?=\}\,\{)")
bill8_first=$(echo $bill8raw_first | awk '{print $8}')
id8raw_first=$(echo $page_stripped_first | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id8_first=$(echo $id8raw_first | awk '{print $8}')
title8raw_first=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title8_first=$(echo $title8raw_first | awk '{print $8}')
sponsor8raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor8_first=$(echo $sponsor8raw_first | awk '{print $8}')
sponsorst8raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst8_first=$(echo $sponsorst8raw_first | awk '{print $8}')
sponsorpar8raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar8_first=$(echo $sponsorpar8raw_first | awk '{print $8}')
date8raw_first=$(echo $page_stripped_first | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date8_first=$(echo $date8raw_first | awk '{print $8}')
house8raw_first=$(echo $page_stripped_first | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house8_first=$(echo $house8raw_first | awk '{print $8}')
senate8raw_first=$(echo $page_stripped_first | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate8_first=$(echo $senate8raw_first | awk '{print $8}')
enacted8raw_first=$(echo $page_stripped_first | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted8_first=$(echo $enacted8raw_first | awk '{print $8}')
sponsor8raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor8_first=$(echo $sponsor8raw_first | awk '{print $8}')
last_action_date8raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date8_first=$(echo $last_action_date8raw_first | awk '{print $8}')
last_action8raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action8_first=$(echo $last_action8raw_first | awk '{print $8}')
url8raw_first=$(echo $page_stripped_first | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url8_first=$(echo $url8raw_first | awk '{print $8}')

echo "$i | $id8_first | $title8_first | $sponsor8_first | $sponsorst8_first | $sponsorpar8_first | $date8_first | $house8_first | $senate8_first | $enacted8_first | $last_action_date8_first | $last_action8_first | $url8_first"
echo "$i|$id8_first|$title8_first|$sponsor8_first|$sponsorst8_first|$sponsorpar8_first|$date8_first|$house8_first|$senate8_first|$enacted8_first|$last_action_date8_first|$last_action8_first|$url8_first" >> house-bills.txt

#bill9
bill9raw_first=$(echo $page_stripped_first | grep -oP "bill_id.*?(?=\}\,\{)")
bill9_first=$(echo $bill9raw_first | awk '{print $9}')
id9raw_first=$(echo $page_stripped_first | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id9_first=$(echo $id9raw_first | awk '{print $9}')
title9raw_first=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title9_first=$(echo $title9raw_first | awk '{print $9}')
sponsor9raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor9_first=$(echo $sponsor9raw_first | awk '{print $9}')
sponsorst9raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst9_first=$(echo $sponsorst9raw_first | awk '{print $9}')
sponsorpar9raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar9_first=$(echo $sponsorpar9raw_first | awk '{print $9}')
date9raw_first=$(echo $page_stripped_first | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date9_first=$(echo $date9raw_first | awk '{print $9}')
house9raw_first=$(echo $page_stripped_first | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house9_first=$(echo $house9raw_first | awk '{print $9}')
senate9raw_first=$(echo $page_stripped_first | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate9_first=$(echo $senate9raw_first | awk '{print $9}')
enacted9raw_first=$(echo $page_stripped_first | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted9_first=$(echo $enacted9raw_first | awk '{print $9}')
sponsor9raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor9_first=$(echo $sponsor9raw_first | awk '{print $9}')
last_action_date9raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date9_first=$(echo $last_action_date9raw_first | awk '{print $9}')
last_action9raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action9_first=$(echo $last_action9raw_first | awk '{print $9}')
url9raw_first=$(echo $page_stripped_first | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url9_first=$(echo $url9raw_first | awk '{print $9}')

echo "$i | $id9_first | $title9_first | $sponsor9_first | $sponsorst9_first | $sponsorpar9_first | $date9_first | $house9_first | $senate9_first | $enacted9_first | $last_action_date9_first | $last_action9_first | $url9_first"
echo "$i|$id9_first|$title9_first|$sponsor9_first|$sponsorst9_first|$sponsorpar9_first|$date9_first|$house9_first|$senate9_first|$enacted9_first|$last_action_date9_first|$last_action9_first|$url9_first" >> house-bills.txt

#bill10
bill10raw_first=$(echo $page_stripped_first | grep -oP "bill_id.*?(?=\}\,\{)")
bill10_first=$(echo $bill10raw_first | awk '{print $10}')
id10raw_first=$(echo $page_stripped_first | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id10_first=$(echo $id10raw_first | awk '{print $10}')
title10raw_first=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title10_first=$(echo $title10raw_first | awk '{print $10}')
sponsor10raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor10_first=$(echo $sponsor10raw_first | awk '{print $10}')
sponsorst10raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst10_first=$(echo $sponsorst10raw_first | awk '{print $10}')
sponsorpar10raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar10_first=$(echo $sponsorpar10raw_first | awk '{print $10}')
date10raw_first=$(echo $page_stripped_first | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date10_first=$(echo $date10raw_first | awk '{print $10}')
house10raw_first=$(echo $page_stripped_first | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house10_first=$(echo $house10raw_first | awk '{print $10}')
senate10raw_first=$(echo $page_stripped_first | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate10_first=$(echo $senate10raw_first | awk '{print $10}')
enacted10raw_first=$(echo $page_stripped_first | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted10_first=$(echo $enacted10raw_first | awk '{print $10}')
sponsor10raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor10_first=$(echo $sponsor10raw_first | awk '{print $10}')
last_action_date10raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date10_first=$(echo $last_action_date10raw_first | awk '{print $10}')
last_action10raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action10_first=$(echo $last_action10raw_first | awk '{print $10}')
url10raw_first=$(echo $page_stripped_first | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url10_first=$(echo $url10raw_first | awk '{print $10}')

echo "$i | $id10_first | $title10_first | $sponsor10_first | $sponsorst10_first | $sponsorpar10_first | $date10_first | $house10_first | $senate10_first | $enacted10_first | $last_action_date10_first | $last_action10_first | $url10_first"
echo "$i|$id10_first|$title10_first|$sponsor10_first|$sponsorst10_first|$sponsorpar10_first|$date10_first|$house10_first|$senate10_first|$enacted10_first|$last_action_date10_first|$last_action10_first|$url10_first" >> house-bills.txt

#bill11
bill11raw_first=$(echo $page_stripped_first | grep -oP "bill_id.*?(?=\}\,\{)")
bill11_first=$(echo $bill11raw_first | awk '{print $11}')
id11raw_first=$(echo $page_stripped_first | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id11_first=$(echo $id11raw_first | awk '{print $11}')
title11raw_first=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title11_first=$(echo $title11raw_first | awk '{print $11}')
sponsor11raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor11_first=$(echo $sponsor11raw_first | awk '{print $11}')
sponsorst11raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst11_first=$(echo $sponsorst11raw_first | awk '{print $11}')
sponsorpar11raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar11_first=$(echo $sponsorpar11raw_first | awk '{print $11}')
date11raw_first=$(echo $page_stripped_first | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date11_first=$(echo $date11raw_first | awk '{print $11}')
house11raw_first=$(echo $page_stripped_first | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house11_first=$(echo $house11raw_first | awk '{print $11}')
senate11raw_first=$(echo $page_stripped_first | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate11_first=$(echo $senate11raw_first | awk '{print $11}')
enacted11raw_first=$(echo $page_stripped_first | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted11_first=$(echo $enacted11raw_first | awk '{print $11}')
sponsor11raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor11_first=$(echo $sponsor11raw_first | awk '{print $11}')
last_action_date11raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date11_first=$(echo $last_action_date11raw_first | awk '{print $11}')
last_action11raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action11_first=$(echo $last_action11raw_first | awk '{print $11}')
url11raw_first=$(echo $page_stripped_first | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url11_first=$(echo $url11raw_first | awk '{print $11}')

echo "$i | $id11_first | $title11_first | $sponsor11_first | $sponsorst11_first | $sponsorpar11_first | $date11_first | $house11_first | $senate11_first | $enacted11_first | $last_action_date11_first | $last_action11_first | $url11_first"
echo "$i|$id11_first|$title11_first|$sponsor11_first|$sponsorst11_first|$sponsorpar11_first|$date11_first|$house11_first|$senate11_first|$enacted11_first|$last_action_date11_first|$last_action11_first|$url11_first" >> house-bills.txt

#bill12
bill12raw_first=$(echo $page_stripped_first | grep -oP "bill_id.*?(?=\}\,\{)")
bill12_first=$(echo $bill12raw_first | awk '{print $12}')
id12raw_first=$(echo $page_stripped_first | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id12_first=$(echo $id12raw_first | awk '{print $12}')
title12raw_first=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title12_first=$(echo $title12raw_first | awk '{print $12}')
sponsor12raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor12_first=$(echo $sponsor12raw_first | awk '{print $12}')
sponsorst12raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst12_first=$(echo $sponsorst12raw_first | awk '{print $12}')
sponsorpar12raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar12_first=$(echo $sponsorpar12raw_first | awk '{print $12}')
date12raw_first=$(echo $page_stripped_first | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date12_first=$(echo $date12raw_first | awk '{print $12}')
house12raw_first=$(echo $page_stripped_first | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house12_first=$(echo $house12raw_first | awk '{print $12}')
senate12raw_first=$(echo $page_stripped_first | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate12_first=$(echo $senate12raw_first | awk '{print $12}')
enacted12raw_first=$(echo $page_stripped_first | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted12_first=$(echo $enacted12raw_first | awk '{print $12}')
sponsor12raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor12_first=$(echo $sponsor12raw_first | awk '{print $12}')
last_action_date12raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date12_first=$(echo $last_action_date12raw_first | awk '{print $12}')
last_action12raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action12_first=$(echo $last_action12raw_first | awk '{print $12}')
url12raw_first=$(echo $page_stripped_first | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url12_first=$(echo $url12raw_first | awk '{print $12}')

echo "$i | $id12_first | $title12_first | $sponsor12_first | $sponsorst12_first | $sponsorpar12_first | $date12_first | $house12_first | $senate12_first | $enacted12_first | $last_action_date12_first | $last_action12_first | $url12_first"
echo "$i|$id12_first|$title12_first|$sponsor12_first|$sponsorst12_first|$sponsorpar12_first|$date12_first|$house12_first|$senate12_first|$enacted12_first|$last_action_date12_first|$last_action12_first|$url12_first" >> house-bills.txt

#bill13
bill13raw_first=$(echo $page_stripped_first | grep -oP "bill_id.*?(?=\}\,\{)")
bill13_first=$(echo $bill13raw_first | awk '{print $13}')
id13raw_first=$(echo $page_stripped_first | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id13_first=$(echo $id13raw_first | awk '{print $13}')
title13raw_first=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title13_first=$(echo $title13raw_first | awk '{print $13}')
sponsor13raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor13_first=$(echo $sponsor13raw_first | awk '{print $13}')
sponsorst13raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst13_first=$(echo $sponsorst13raw_first | awk '{print $13}')
sponsorpar13raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar13_first=$(echo $sponsorpar13raw_first | awk '{print $13}')
date13raw_first=$(echo $page_stripped_first | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date13_first=$(echo $date13raw_first | awk '{print $13}')
house13raw_first=$(echo $page_stripped_first | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house13_first=$(echo $house13raw_first | awk '{print $13}')
senate13raw_first=$(echo $page_stripped_first | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate13_first=$(echo $senate13raw_first | awk '{print $13}')
enacted13raw_first=$(echo $page_stripped_first | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted13_first=$(echo $enacted13raw_first | awk '{print $13}')
sponsor13raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor13_first=$(echo $sponsor13raw_first | awk '{print $13}')
last_action_date13raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date13_first=$(echo $last_action_date13raw_first | awk '{print $13}')
last_action13raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action13_first=$(echo $last_action13raw_first | awk '{print $13}')
url13raw_first=$(echo $page_stripped_first | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url13_first=$(echo $url13raw_first | awk '{print $13}')

echo "$i | $id13_first | $title13_first | $sponsor13_first | $sponsorst13_first | $sponsorpar13_first | $date13_first | $house13_first | $senate13_first | $enacted13_first | $last_action_date13_first | $last_action13_first | $url13_first"
echo "$i|$id13_first|$title13_first|$sponsor13_first|$sponsorst13_first|$sponsorpar13_first|$date13_first|$house13_first|$senate13_first|$enacted13_first|$last_action_date13_first|$last_action13_first|$url13_first" >> house-bills.txt

#bill14
bill14raw_first=$(echo $page_stripped_first | grep -oP "bill_id.*?(?=\}\,\{)")
bill14_first=$(echo $bill14raw_first | awk '{print $14}')
id14raw_first=$(echo $page_stripped_first | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id14_first=$(echo $id14raw_first | awk '{print $14}')
title14raw_first=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title14_first=$(echo $title14raw_first | awk '{print $14}')
sponsor14raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor14_first=$(echo $sponsor14raw_first | awk '{print $14}')
sponsorst14raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst14_first=$(echo $sponsorst14raw_first | awk '{print $14}')
sponsorpar14raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar14_first=$(echo $sponsorpar14raw_first | awk '{print $14}')
date14raw_first=$(echo $page_stripped_first | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date14_first=$(echo $date14raw_first | awk '{print $14}')
house14raw_first=$(echo $page_stripped_first | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house14_first=$(echo $house14raw_first | awk '{print $14}')
senate14raw_first=$(echo $page_stripped_first | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate14_first=$(echo $senate14raw_first | awk '{print $14}')
enacted14raw_first=$(echo $page_stripped_first | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted14_first=$(echo $enacted14raw_first | awk '{print $14}')
sponsor14raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor14_first=$(echo $sponsor14raw_first | awk '{print $14}')
last_action_date14raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date14_first=$(echo $last_action_date14raw_first | awk '{print $14}')
last_action14raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action14_first=$(echo $last_action14raw_first | awk '{print $14}')
url14raw_first=$(echo $page_stripped_first | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url14_first=$(echo $url14raw_first | awk '{print $14}')

echo "$i | $id14_first | $title14_first | $sponsor14_first | $sponsorst14_first | $sponsorpar14_first | $date14_first | $house14_first | $senate14_first | $enacted14_first | $last_action_date14_first | $last_action14_first | $url14_first"
echo "$i|$id14_first|$title14_first|$sponsor14_first|$sponsorst14_first|$sponsorpar14_first|$date14_first|$house14_first|$senate14_first|$enacted14_first|$last_action_date14_first|$last_action14_first|$url14_first" >> house-bills.txt

#bill15
bill15raw_first=$(echo $page_stripped_first | grep -oP "bill_id.*?(?=\}\,\{)")
bill15_first=$(echo $bill15raw_first | awk '{print $15}')
id15raw_first=$(echo $page_stripped_first | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id15_first=$(echo $id15raw_first | awk '{print $15}')
title15raw_first=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title15_first=$(echo $title15raw_first | awk '{print $15}')
sponsor15raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor15_first=$(echo $sponsor15raw_first | awk '{print $15}')
sponsorst15raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst15_first=$(echo $sponsorst15raw_first | awk '{print $15}')
sponsorpar15raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar15_first=$(echo $sponsorpar15raw_first | awk '{print $15}')
date15raw_first=$(echo $page_stripped_first | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date15_first=$(echo $date15raw_first | awk '{print $15}')
house15raw_first=$(echo $page_stripped_first | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house15_first=$(echo $house15raw_first | awk '{print $15}')
senate15raw_first=$(echo $page_stripped_first | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate15_first=$(echo $senate15raw_first | awk '{print $15}')
enacted15raw_first=$(echo $page_stripped_first | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted15_first=$(echo $enacted15raw_first | awk '{print $15}')
sponsor15raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor15_first=$(echo $sponsor15raw_first | awk '{print $15}')
last_action_date15raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date15_first=$(echo $last_action_date15raw_first | awk '{print $15}')
last_action15raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action15_first=$(echo $last_action15raw_first | awk '{print $15}')
url15raw_first=$(echo $page_stripped_first | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url15_first=$(echo $url15raw_first | awk '{print $15}')

echo "$i | $id15_first | $title15_first | $sponsor15_first | $sponsorst15_first | $sponsorpar15_first | $date15_first | $house15_first | $senate15_first | $enacted15_first | $last_action_date15_first | $last_action15_first | $url15_first"
echo "$i|$id15_first|$title15_first|$sponsor15_first|$sponsorst15_first|$sponsorpar15_first|$date15_first|$house15_first|$senate15_first|$enacted15_first|$last_action_date15_first|$last_action15_first|$url15_first" >> house-bills.txt

#bill16
bill16raw_first=$(echo $page_stripped_first | grep -oP "bill_id.*?(?=\}\,\{)")
bill16_first=$(echo $bill16raw_first | awk '{print $16}')
id16raw_first=$(echo $page_stripped_first | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id16_first=$(echo $id16raw_first | awk '{print $16}')
title16raw_first=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title16_first=$(echo $title16raw_first | awk '{print $16}')
sponsor16raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor16_first=$(echo $sponsor16raw_first | awk '{print $16}')
sponsorst16raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst16_first=$(echo $sponsorst16raw_first | awk '{print $16}')
sponsorpar16raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar16_first=$(echo $sponsorpar16raw_first | awk '{print $16}')
date16raw_first=$(echo $page_stripped_first | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date16_first=$(echo $date16raw_first | awk '{print $16}')
house16raw_first=$(echo $page_stripped_first | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house16_first=$(echo $house16raw_first | awk '{print $16}')
senate16raw_first=$(echo $page_stripped_first | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate16_first=$(echo $senate16raw_first | awk '{print $16}')
enacted16raw_first=$(echo $page_stripped_first | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted16_first=$(echo $enacted16raw_first | awk '{print $16}')
sponsor16raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor16_first=$(echo $sponsor16raw_first | awk '{print $16}')
last_action_date16raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date16_first=$(echo $last_action_date16raw_first | awk '{print $16}')
last_action16raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action16_first=$(echo $last_action16raw_first | awk '{print $16}')
url16raw_first=$(echo $page_stripped_first | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url16_first=$(echo $url16raw_first | awk '{print $16}')

echo "$i | $id16_first | $title16_first | $sponsor16_first | $sponsorst16_first | $sponsorpar16_first | $date16_first | $house16_first | $senate16_first | $enacted16_first | $last_action_date16_first | $last_action16_first | $url16_first"
echo "$i|$id16_first|$title16_first|$sponsor16_first|$sponsorst16_first|$sponsorpar16_first|$date16_first|$house16_first|$senate16_first|$enacted16_first|$last_action_date16_first|$last_action16_first|$url16_first" >> house-bills.txt

#bill17
bill17raw_first=$(echo $page_stripped_first | grep -oP "bill_id.*?(?=\}\,\{)")
bill17_first=$(echo $bill17raw_first | awk '{print $17}')
id17raw_first=$(echo $page_stripped_first | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id17_first=$(echo $id17raw_first | awk '{print $17}')
title17raw_first=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title17_first=$(echo $title17raw_first | awk '{print $17}')
sponsor17raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor17_first=$(echo $sponsor17raw_first | awk '{print $17}')
sponsorst17raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst17_first=$(echo $sponsorst17raw_first | awk '{print $17}')
sponsorpar17raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar17_first=$(echo $sponsorpar17raw_first | awk '{print $17}')
date17raw_first=$(echo $page_stripped_first | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date17_first=$(echo $date17raw_first | awk '{print $17}')
house17raw_first=$(echo $page_stripped_first | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house17_first=$(echo $house17raw_first | awk '{print $17}')
senate17raw_first=$(echo $page_stripped_first | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate17_first=$(echo $senate17raw_first | awk '{print $17}')
enacted17raw_first=$(echo $page_stripped_first | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted17_first=$(echo $enacted17raw_first | awk '{print $17}')
sponsor17raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor17_first=$(echo $sponsor17raw_first | awk '{print $17}')
last_action_date17raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date17_first=$(echo $last_action_date17raw_first | awk '{print $17}')
last_action17raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action17_first=$(echo $last_action17raw_first | awk '{print $17}')
url17raw_first=$(echo $page_stripped_first | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url17_first=$(echo $url17raw_first | awk '{print $17}')

echo "$i | $id17_first | $title17_first | $sponsor17_first | $sponsorst17_first | $sponsorpar17_first | $date17_first | $house17_first | $senate17_first | $enacted17_first | $last_action_date17_first | $last_action17_first | $url17_first"
echo "$i|$id17_first|$title17_first|$sponsor17_first|$sponsorst17_first|$sponsorpar17_first|$date17_first|$house17_first|$senate17_first|$enacted17_first|$last_action_date17_first|$last_action17_first|$url17_first" >> house-bills.txt

#bill18
bill18raw_first=$(echo $page_stripped_first | grep -oP "bill_id.*?(?=\}\,\{)")
bill18_first=$(echo $bill18raw_first | awk '{print $18}')
id18raw_first=$(echo $page_stripped_first | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id18_first=$(echo $id18raw_first | awk '{print $18}')
title18raw_first=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title18_first=$(echo $title18raw_first | awk '{print $18}')
sponsor18raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor18_first=$(echo $sponsor18raw_first | awk '{print $18}')
sponsorst18raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst18_first=$(echo $sponsorst18raw_first | awk '{print $18}')
sponsorpar18raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar18_first=$(echo $sponsorpar18raw_first | awk '{print $18}')
date18raw_first=$(echo $page_stripped_first | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date18_first=$(echo $date18raw_first | awk '{print $18}')
house18raw_first=$(echo $page_stripped_first | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house18_first=$(echo $house18raw_first | awk '{print $18}')
senate18raw_first=$(echo $page_stripped_first | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate18_first=$(echo $senate18raw_first | awk '{print $18}')
enacted18raw_first=$(echo $page_stripped_first | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted18_first=$(echo $enacted18raw_first | awk '{print $18}')
sponsor18raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor18_first=$(echo $sponsor18raw_first | awk '{print $18}')
last_action_date18raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date18_first=$(echo $last_action_date18raw_first | awk '{print $18}')
last_action18raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action18_first=$(echo $last_action18raw_first | awk '{print $18}')
url18raw_first=$(echo $page_stripped_first | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url18_first=$(echo $url18raw_first | awk '{print $18}')

echo "$i | $id18_first | $title18_first | $sponsor18_first | $sponsorst18_first | $sponsorpar18_first | $date18_first | $house18_first | $senate18_first | $enacted18_first | $last_action_date18_first | $last_action18_first | $url18_first"
echo "$i|$id18_first|$title18_first|$sponsor18_first|$sponsorst18_first|$sponsorpar18_first|$date18_first|$house18_first|$senate18_first|$enacted18_first|$last_action_date18_first|$last_action18_first|$url18_first" >> house-bills.txt

#bill19
bill19raw_first=$(echo $page_stripped_first | grep -oP "bill_id.*?(?=\}\,\{)")
bill19_first=$(echo $bill19raw_first | awk '{print $19}')
id19raw_first=$(echo $page_stripped_first | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id19_first=$(echo $id19raw_first | awk '{print $19}')
title19raw_first=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title19_first=$(echo $title19raw_first | awk '{print $19}')
sponsor19raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor19_first=$(echo $sponsor19raw_first | awk '{print $19}')
sponsorst19raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst19_first=$(echo $sponsorst19raw_first | awk '{print $19}')
sponsorpar19raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar19_first=$(echo $sponsorpar19raw_first | awk '{print $19}')
date19raw_first=$(echo $page_stripped_first | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date19_first=$(echo $date19raw_first | awk '{print $19}')
house19raw_first=$(echo $page_stripped_first | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house19_first=$(echo $house19raw_first | awk '{print $19}')
senate19raw_first=$(echo $page_stripped_first | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate19_first=$(echo $senate19raw_first | awk '{print $19}')
enacted19raw_first=$(echo $page_stripped_first | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted19_first=$(echo $enacted19raw_first | awk '{print $19}')
sponsor19raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor19_first=$(echo $sponsor19raw_first | awk '{print $19}')
last_action_date19raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date19_first=$(echo $last_action_date19raw_first | awk '{print $19}')
last_action19raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action19_first=$(echo $last_action19raw_first | awk '{print $19}')
url19raw_first=$(echo $page_stripped_first | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url19_first=$(echo $url19raw_first | awk '{print $19}')

echo "$i | $id19_first | $title19_first | $sponsor19_first | $sponsorst19_first | $sponsorpar19_first | $date19_first | $house19_first | $senate19_first | $enacted19_first | $last_action_date19_first | $last_action19_first | $url19_first"
echo "$i|$id19_first|$title19_first|$sponsor19_first|$sponsorst19_first|$sponsorpar19_first|$date19_first|$house19_first|$senate19_first|$enacted19_first|$last_action_date19_first|$last_action19_first|$url19_first" >> house-bills.txt

#bill20
bill20raw_first=$(echo $page_stripped_first | grep -oP "bill_id.*?(?=\}\,\{)")
bill20_first=$(echo $bill20raw_first | awk '{print $20}')
id20raw_first=$(echo $page_stripped_first | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id20_first=$(echo $id20raw_first | awk '{print $20}')
title20raw_first=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title20_first=$(echo $title20raw_first | awk '{print $20}')
sponsor20raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor20_first=$(echo $sponsor20raw_first | awk '{print $20}')
sponsorst20raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst20_first=$(echo $sponsorst20raw_first | awk '{print $20}')
sponsorpar20raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar20_first=$(echo $sponsorpar20raw_first | awk '{print $20}')
date20raw_first=$(echo $page_stripped_first | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date20_first=$(echo $date20raw_first | awk '{print $20}')
house20raw_first=$(echo $page_stripped_first | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house20_first=$(echo $house20raw_first | awk '{print $20}')
senate20raw_first=$(echo $page_stripped_first | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate20_first=$(echo $senate20raw_first | awk '{print $20}')
enacted20raw_first=$(echo $page_stripped_first | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted20_first=$(echo $enacted20raw_first | awk '{print $20}')
sponsor20raw_first=$(echo $page_stripped_first | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor20_first=$(echo $sponsor20raw_first | awk '{print $20}')
last_action_date20raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date20_first=$(echo $last_action_date20raw_first | awk '{print $20}')
last_action20raw_first=$(echo $page_stripped_first | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action20_first=$(echo $last_action20raw_first | awk '{print $20}')
url20raw_first=$(echo $page_stripped_first | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url20_first=$(echo $url20raw_first | awk '{print $20}')

echo "$i | $id20_first | $title20_first | $sponsor20_first | $sponsorst20_first | $sponsorpar20_first | $date20_first | $house20_first | $senate20_first | $enacted20_first | $last_action_date20_first | $last_action20_first | $url20_first"
echo "$i|$id20_first|$title20_first|$sponsor20_first|$sponsorst20_first|$sponsorpar20_first|$date20_first|$house20_first|$senate20_first|$enacted20_first|$last_action_date20_first|$last_action20_first|$url20_first" >> house-bills.txt

#iterate over pages (up through 43, which would cover 860 bills in a single congress)
for y in {1..563} #563 pre 113th, change to 43 113th and later.
do
z=$(($y * 20))
url="$url_base?offset=$z"

#pulls json of bills (20 bills per page)
page=$(curl -H 'X-Api-Key: yBBnkhPGVzmNG1IXNP74mVMUNFJa9uHCZBVFspDh' $url)
#raw curl in case you need it curl -H 'X-Api-Key: yBBnkhPGVzmNG1IXNP74mVMUNFJa9uHCZBVFspDh' https://api.propublica.org/congress/v1/105/house/bills/introduced.json?offset=20

#strips spaces
page_stripped="$(echo -e "${page}" | sed -e ':a;N;$!ba;s/\n//g' -e 's/\s//g')"

#replaces spaces with _ (for titles)
title_list="$(echo -e "${page}" | sed -e 's/\s/_/g')"

#bill1
bill1raw=$(echo $page_stripped | grep -oP "bill_id.*?(?=\}\,\{)")
bill1=$(echo $bill1raw | awk '{print $1}')
id1raw=$(echo $page_stripped | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id1=$(echo $id1raw | awk '{print $1}')
title1raw=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title1=$(echo $title1raw | awk '{print $1}')
sponsor1raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor1=$(echo $sponsor1raw | awk '{print $1}')
sponsorst1raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst1=$(echo $sponsorst1raw | awk '{print $1}')
sponsorpar1raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar1=$(echo $sponsorpar1raw | awk '{print $1}')
date1raw=$(echo $page_stripped | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date1=$(echo $date1raw | awk '{print $1}')
house1raw=$(echo $page_stripped | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house1=$(echo $house1raw | awk '{print $1}')
senate1raw=$(echo $page_stripped | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate1=$(echo $senate1raw | awk '{print $1}')
enacted1raw=$(echo $page_stripped | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted1=$(echo $enacted1raw | awk '{print $1}')
sponsor1raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor1=$(echo $sponsor1raw | awk '{print $1}')
last_action_date1raw=$(echo $page_stripped | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date1=$(echo $last_action_date1raw | awk '{print $1}')
last_action1raw=$(echo $page_stripped | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action1=$(echo $last_action1raw | awk '{print $1}')
url1raw=$(echo $page_stripped | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url1=$(echo $url1raw | awk '{print $1}')

echo "$i | $id1 | $title1 | $sponsor1 | $sponsorst1 | $sponsorpar1 | $date1 | $house1 | $senate1 | $enacted1 | $last_action_date1 | $last_action1 | $url1"
echo "$i|$id1|$title1|$sponsor1|$sponsorst1|$sponsorpar1|$date1|$house1|$senate1|$enacted1|$last_action_date1|$last_action1|$url1" >> house-bills.txt

#bill2
bill2raw=$(echo $page_stripped | grep -oP "bill_id.*?(?=\}\,\{)")
bill2=$(echo $bill2raw | awk '{print $2}')
id2raw=$(echo $page_stripped | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id2=$(echo $id2raw | awk '{print $2}')
title2raw=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title2=$(echo $title2raw | awk '{print $2}')
sponsor2raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor2=$(echo $sponsor2raw | awk '{print $2}')
sponsorst2raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst2=$(echo $sponsorst2raw | awk '{print $2}')
sponsorpar2raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar2=$(echo $sponsorpar2raw | awk '{print $2}')
date2raw=$(echo $page_stripped | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date2=$(echo $date2raw | awk '{print $2}')
house2raw=$(echo $page_stripped | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house2=$(echo $house2raw | awk '{print $2}')
senate2raw=$(echo $page_stripped | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate2=$(echo $senate2raw | awk '{print $2}')
enacted2raw=$(echo $page_stripped | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted2=$(echo $enacted2raw | awk '{print $2}')
sponsor2raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor2=$(echo $sponsor2raw | awk '{print $2}')
last_action_date2raw=$(echo $page_stripped | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date2=$(echo $last_action_date2raw | awk '{print $2}')
last_action2raw=$(echo $page_stripped | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action2=$(echo $last_action2raw | awk '{print $2}')
url2raw=$(echo $page_stripped | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url2=$(echo $url2raw | awk '{print $2}')

echo "$i | $id2 | $title2 | $sponsor2 | $sponsorst2 | $sponsorpar2 | $date2 | $house2 | $senate2 | $enacted2 | $last_action_date2 | $last_action2 | $url2"
echo "$i|$id2|$title2|$sponsor2|$sponsorst2|$sponsorpar2|$date2|$house2|$senate2|$enacted2|$last_action_date2|$last_action2|$url2" >> house-bills.txt

#bill3
bill3raw=$(echo $page_stripped | grep -oP "bill_id.*?(?=\}\,\{)")
bill3=$(echo $bill3raw | awk '{print $3}')
id3raw=$(echo $page_stripped | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id3=$(echo $id3raw | awk '{print $3}')
title3raw=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title3=$(echo $title3raw | awk '{print $3}')
sponsor3raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor3=$(echo $sponsor3raw | awk '{print $3}')
sponsorst3raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst3=$(echo $sponsorst3raw | awk '{print $3}')
sponsorpar3raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar3=$(echo $sponsorpar3raw | awk '{print $3}')
date3raw=$(echo $page_stripped | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date3=$(echo $date3raw | awk '{print $3}')
house3raw=$(echo $page_stripped | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house3=$(echo $house3raw | awk '{print $3}')
senate3raw=$(echo $page_stripped | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate3=$(echo $senate3raw | awk '{print $3}')
enacted3raw=$(echo $page_stripped | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted3=$(echo $enacted3raw | awk '{print $3}')
sponsor3raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor3=$(echo $sponsor3raw | awk '{print $3}')
last_action_date3raw=$(echo $page_stripped | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date3=$(echo $last_action_date3raw | awk '{print $3}')
last_action3raw=$(echo $page_stripped | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action3=$(echo $last_action3raw | awk '{print $3}')
url3raw=$(echo $page_stripped | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url3=$(echo $url3raw | awk '{print $3}')

echo "$i | $id3 | $title3 | $sponsor3 | $sponsorst3 | $sponsorpar3 | $date3 | $house3 | $senate3 | $enacted3 | $last_action_date3 | $last_action3 | $url3"
echo "$i|$id3|$title3|$sponsor3|$sponsorst3|$sponsorpar3|$date3|$house3|$senate3|$enacted3|$last_action_date3|$last_action3|$url3" >> house-bills.txt

#bill4
bill4raw=$(echo $page_stripped | grep -oP "bill_id.*?(?=\}\,\{)")
bill4=$(echo $bill4raw | awk '{print $4}')
id4raw=$(echo $page_stripped | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id4=$(echo $id4raw | awk '{print $4}')
title4raw=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title4=$(echo $title4raw | awk '{print $4}')
sponsor4raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor4=$(echo $sponsor4raw | awk '{print $4}')
sponsorst4raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst4=$(echo $sponsorst4raw | awk '{print $4}')
sponsorpar4raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar4=$(echo $sponsorpar4raw | awk '{print $4}')
date4raw=$(echo $page_stripped | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date4=$(echo $date4raw | awk '{print $4}')
house4raw=$(echo $page_stripped | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house4=$(echo $house4raw | awk '{print $4}')
senate4raw=$(echo $page_stripped | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate4=$(echo $senate4raw | awk '{print $4}')
enacted4raw=$(echo $page_stripped | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted4=$(echo $enacted4raw | awk '{print $4}')
sponsor4raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor4=$(echo $sponsor4raw | awk '{print $4}')
last_action_date4raw=$(echo $page_stripped | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date4=$(echo $last_action_date4raw | awk '{print $4}')
last_action4raw=$(echo $page_stripped | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action4=$(echo $last_action4raw | awk '{print $4}')
url4raw=$(echo $page_stripped | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url4=$(echo $url4raw | awk '{print $4}')

echo "$i | $id4 | $title4 | $sponsor4 | $sponsorst4 | $sponsorpar4 | $date4 | $house4 | $senate4 | $enacted4 | $last_action_date4 | $last_action4 | $url4"
echo "$i|$id4|$title4|$sponsor4|$sponsorst4|$sponsorpar4|$date4|$house4|$senate4|$enacted4|$last_action_date4|$last_action4|$url4" >> house-bills.txt

#bill5
bill5raw=$(echo $page_stripped | grep -oP "bill_id.*?(?=\}\,\{)")
bill5=$(echo $bill5raw | awk '{print $5}')
id5raw=$(echo $page_stripped | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id5=$(echo $id5raw | awk '{print $5}')
title5raw=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title5=$(echo $title5raw | awk '{print $5}')
sponsor5raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor5=$(echo $sponsor5raw | awk '{print $5}')
sponsorst5raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst5=$(echo $sponsorst5raw | awk '{print $5}')
sponsorpar5raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar5=$(echo $sponsorpar5raw | awk '{print $5}')
date5raw=$(echo $page_stripped | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date5=$(echo $date5raw | awk '{print $5}')
house5raw=$(echo $page_stripped | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house5=$(echo $house5raw | awk '{print $5}')
senate5raw=$(echo $page_stripped | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate5=$(echo $senate5raw | awk '{print $5}')
enacted5raw=$(echo $page_stripped | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted5=$(echo $enacted5raw | awk '{print $5}')
sponsor5raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor5=$(echo $sponsor5raw | awk '{print $5}')
last_action_date5raw=$(echo $page_stripped | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date5=$(echo $last_action_date5raw | awk '{print $5}')
last_action5raw=$(echo $page_stripped | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action5=$(echo $last_action5raw | awk '{print $5}')
url5raw=$(echo $page_stripped | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url5=$(echo $url5raw | awk '{print $5}')

echo "$i | $id5 | $title5 | $sponsor5 | $sponsorst5 | $sponsorpar5 | $date5 | $house5 | $senate5 | $enacted5 | $last_action_date5 | $last_action5 | $url5"
echo "$i|$id5|$title5|$sponsor5|$sponsorst5|$sponsorpar5|$date5|$house5|$senate5|$enacted5|$last_action_date5|$last_action5|$url5" >> house-bills.txt

#bill6
bill6raw=$(echo $page_stripped | grep -oP "bill_id.*?(?=\}\,\{)")
bill6=$(echo $bill6raw | awk '{print $6}')
id6raw=$(echo $page_stripped | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id6=$(echo $id6raw | awk '{print $6}')
title6raw=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title6=$(echo $title6raw | awk '{print $6}')
sponsor6raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor6=$(echo $sponsor6raw | awk '{print $6}')
sponsorst6raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst6=$(echo $sponsorst6raw | awk '{print $6}')
sponsorpar6raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar6=$(echo $sponsorpar6raw | awk '{print $6}')
date6raw=$(echo $page_stripped | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date6=$(echo $date6raw | awk '{print $6}')
house6raw=$(echo $page_stripped | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house6=$(echo $house6raw | awk '{print $6}')
senate6raw=$(echo $page_stripped | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate6=$(echo $senate6raw | awk '{print $6}')
enacted6raw=$(echo $page_stripped | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted6=$(echo $enacted6raw | awk '{print $6}')
sponsor6raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor6=$(echo $sponsor6raw | awk '{print $6}')
last_action_date6raw=$(echo $page_stripped | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date6=$(echo $last_action_date6raw | awk '{print $6}')
last_action6raw=$(echo $page_stripped | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action6=$(echo $last_action6raw | awk '{print $6}')
url6raw=$(echo $page_stripped | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url6=$(echo $url6raw | awk '{print $6}')

echo "$i | $id6 | $title6 | $sponsor6 | $sponsorst6 | $sponsorpar6 | $date6 | $house6 | $senate6 | $enacted6 | $last_action_date6 | $last_action6 | $url6"
echo "$i|$id6|$title6|$sponsor6|$sponsorst6|$sponsorpar6|$date6|$house6|$senate6|$enacted6|$last_action_date6|$last_action6|$url6" >> house-bills.txt

#bill7
bill7raw=$(echo $page_stripped | grep -oP "bill_id.*?(?=\}\,\{)")
bill7=$(echo $bill7raw | awk '{print $7}')
id7raw=$(echo $page_stripped | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id7=$(echo $id7raw | awk '{print $7}')
title7raw=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title7=$(echo $title7raw | awk '{print $7}')
sponsor7raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor7=$(echo $sponsor7raw | awk '{print $7}')
sponsorst7raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst7=$(echo $sponsorst7raw | awk '{print $7}')
sponsorpar7raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar7=$(echo $sponsorpar7raw | awk '{print $7}')
date7raw=$(echo $page_stripped | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date7=$(echo $date7raw | awk '{print $7}')
house7raw=$(echo $page_stripped | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house7=$(echo $house7raw | awk '{print $7}')
senate7raw=$(echo $page_stripped | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate7=$(echo $senate7raw | awk '{print $7}')
enacted7raw=$(echo $page_stripped | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted7=$(echo $enacted7raw | awk '{print $7}')
sponsor7raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor7=$(echo $sponsor7raw | awk '{print $7}')
last_action_date7raw=$(echo $page_stripped | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date7=$(echo $last_action_date7raw | awk '{print $7}')
last_action7raw=$(echo $page_stripped | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action7=$(echo $last_action7raw | awk '{print $7}')
url7raw=$(echo $page_stripped | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url7=$(echo $url7raw | awk '{print $7}')

echo "$i | $id7 | $title7 | $sponsor7 | $sponsorst7 | $sponsorpar7 | $date7 | $house7 | $senate7 | $enacted7 | $last_action_date7 | $last_action7 | $url7"
echo "$i|$id7|$title7|$sponsor7|$sponsorst7|$sponsorpar7|$date7|$house7|$senate7|$enacted7|$last_action_date7|$last_action7|$url7" >> house-bills.txt

#bill8
bill8raw=$(echo $page_stripped | grep -oP "bill_id.*?(?=\}\,\{)")
bill8=$(echo $bill8raw | awk '{print $8}')
id8raw=$(echo $page_stripped | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id8=$(echo $id8raw | awk '{print $8}')
title8raw=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title8=$(echo $title8raw | awk '{print $8}')
sponsor8raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor8=$(echo $sponsor8raw | awk '{print $8}')
sponsorst8raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst8=$(echo $sponsorst8raw | awk '{print $8}')
sponsorpar8raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar8=$(echo $sponsorpar8raw | awk '{print $8}')
date8raw=$(echo $page_stripped | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date8=$(echo $date8raw | awk '{print $8}')
house8raw=$(echo $page_stripped | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house8=$(echo $house8raw | awk '{print $8}')
senate8raw=$(echo $page_stripped | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate8=$(echo $senate8raw | awk '{print $8}')
enacted8raw=$(echo $page_stripped | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted8=$(echo $enacted8raw | awk '{print $8}')
sponsor8raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor8=$(echo $sponsor8raw | awk '{print $8}')
last_action_date8raw=$(echo $page_stripped | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date8=$(echo $last_action_date8raw | awk '{print $8}')
last_action8raw=$(echo $page_stripped | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action8=$(echo $last_action8raw | awk '{print $8}')
url8raw=$(echo $page_stripped | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url8=$(echo $url8raw | awk '{print $8}')

echo "$i | $id8 | $title8 | $sponsor8 | $sponsorst8 | $sponsorpar8 | $date8 | $house8 | $senate8 | $enacted8 | $last_action_date8 | $last_action8 | $url8"
echo "$i|$id8|$title8|$sponsor8|$sponsorst8|$sponsorpar8|$date8|$house8|$senate8|$enacted8|$last_action_date8|$last_action8|$url8" >> house-bills.txt

#bill9
bill9raw=$(echo $page_stripped | grep -oP "bill_id.*?(?=\}\,\{)")
bill9=$(echo $bill9raw | awk '{print $9}')
id9raw=$(echo $page_stripped | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id9=$(echo $id9raw | awk '{print $9}')
title9raw=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title9=$(echo $title9raw | awk '{print $9}')
sponsor9raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor9=$(echo $sponsor9raw | awk '{print $9}')
sponsorst9raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst9=$(echo $sponsorst9raw | awk '{print $9}')
sponsorpar9raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar9=$(echo $sponsorpar9raw | awk '{print $9}')
date9raw=$(echo $page_stripped | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date9=$(echo $date9raw | awk '{print $9}')
house9raw=$(echo $page_stripped | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house9=$(echo $house9raw | awk '{print $9}')
senate9raw=$(echo $page_stripped | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate9=$(echo $senate9raw | awk '{print $9}')
enacted9raw=$(echo $page_stripped | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted9=$(echo $enacted9raw | awk '{print $9}')
sponsor9raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor9=$(echo $sponsor9raw | awk '{print $9}')
last_action_date9raw=$(echo $page_stripped | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date9=$(echo $last_action_date9raw | awk '{print $9}')
last_action9raw=$(echo $page_stripped | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action9=$(echo $last_action9raw | awk '{print $9}')
url9raw=$(echo $page_stripped | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url9=$(echo $url9raw | awk '{print $9}')

echo "$i | $id9 | $title9 | $sponsor9 | $sponsorst9 | $sponsorpar9 | $date9 | $house9 | $senate9 | $enacted9 | $last_action_date9 | $last_action9 | $url9"
echo "$i|$id9|$title9|$sponsor9|$sponsorst9|$sponsorpar9|$date9|$house9|$senate9|$enacted9|$last_action_date9|$last_action9|$url9" >> house-bills.txt

#bill10
bill10raw=$(echo $page_stripped | grep -oP "bill_id.*?(?=\}\,\{)")
bill10=$(echo $bill10raw | awk '{print $10}')
id10raw=$(echo $page_stripped | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id10=$(echo $id10raw | awk '{print $10}')
title10raw=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title10=$(echo $title10raw | awk '{print $10}')
sponsor10raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor10=$(echo $sponsor10raw | awk '{print $10}')
sponsorst10raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst10=$(echo $sponsorst10raw | awk '{print $10}')
sponsorpar10raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar10=$(echo $sponsorpar10raw | awk '{print $10}')
date10raw=$(echo $page_stripped | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date10=$(echo $date10raw | awk '{print $10}')
house10raw=$(echo $page_stripped | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house10=$(echo $house10raw | awk '{print $10}')
senate10raw=$(echo $page_stripped | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate10=$(echo $senate10raw | awk '{print $10}')
enacted10raw=$(echo $page_stripped | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted10=$(echo $enacted10raw | awk '{print $10}')
sponsor10raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor10=$(echo $sponsor10raw | awk '{print $10}')
last_action_date10raw=$(echo $page_stripped | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date10=$(echo $last_action_date10raw | awk '{print $10}')
last_action10raw=$(echo $page_stripped | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action10=$(echo $last_action10raw | awk '{print $10}')
url10raw=$(echo $page_stripped | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url10=$(echo $url10raw | awk '{print $10}')

echo "$i | $id10 | $title10 | $sponsor10 | $sponsorst10 | $sponsorpar10 | $date10 | $house10 | $senate10 | $enacted10 | $last_action_date10 | $last_action10 | $url10"
echo "$i|$id10|$title10|$sponsor10|$sponsorst10|$sponsorpar10|$date10|$house10|$senate10|$enacted10|$last_action_date10|$last_action10|$url10" >> house-bills.txt

#bill11
bill11raw=$(echo $page_stripped | grep -oP "bill_id.*?(?=\}\,\{)")
bill11=$(echo $bill11raw | awk '{print $11}')
id11raw=$(echo $page_stripped | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id11=$(echo $id11raw | awk '{print $11}')
title11raw=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title11=$(echo $title11raw | awk '{print $11}')
sponsor11raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor11=$(echo $sponsor11raw | awk '{print $11}')
sponsorst11raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst11=$(echo $sponsorst11raw | awk '{print $11}')
sponsorpar11raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar11=$(echo $sponsorpar11raw | awk '{print $11}')
date11raw=$(echo $page_stripped | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date11=$(echo $date11raw | awk '{print $11}')
house11raw=$(echo $page_stripped | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house11=$(echo $house11raw | awk '{print $11}')
senate11raw=$(echo $page_stripped | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate11=$(echo $senate11raw | awk '{print $11}')
enacted11raw=$(echo $page_stripped | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted11=$(echo $enacted11raw | awk '{print $11}')
sponsor11raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor11=$(echo $sponsor11raw | awk '{print $11}')
last_action_date11raw=$(echo $page_stripped | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date11=$(echo $last_action_date11raw | awk '{print $11}')
last_action11raw=$(echo $page_stripped | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action11=$(echo $last_action11raw | awk '{print $11}')
url11raw=$(echo $page_stripped | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url11=$(echo $url11raw | awk '{print $11}')

echo "$i | $id11 | $title11 | $sponsor11 | $sponsorst11 | $sponsorpar11 | $date11 | $house11 | $senate11 | $enacted11 | $last_action_date11 | $last_action11 | $url11"
echo "$i|$id11|$title11|$sponsor11|$sponsorst11|$sponsorpar11|$date11|$house11|$senate11|$enacted11|$last_action_date11|$last_action11|$url11" >> house-bills.txt

#bill12
bill12raw=$(echo $page_stripped | grep -oP "bill_id.*?(?=\}\,\{)")
bill12=$(echo $bill12raw | awk '{print $12}')
id12raw=$(echo $page_stripped | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id12=$(echo $id12raw | awk '{print $12}')
title12raw=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title12=$(echo $title12raw | awk '{print $12}')
sponsor12raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor12=$(echo $sponsor12raw | awk '{print $12}')
sponsorst12raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst12=$(echo $sponsorst12raw | awk '{print $12}')
sponsorpar12raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar12=$(echo $sponsorpar12raw | awk '{print $12}')
date12raw=$(echo $page_stripped | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date12=$(echo $date12raw | awk '{print $12}')
house12raw=$(echo $page_stripped | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house12=$(echo $house12raw | awk '{print $12}')
senate12raw=$(echo $page_stripped | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate12=$(echo $senate12raw | awk '{print $12}')
enacted12raw=$(echo $page_stripped | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted12=$(echo $enacted12raw | awk '{print $12}')
sponsor12raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor12=$(echo $sponsor12raw | awk '{print $12}')
last_action_date12raw=$(echo $page_stripped | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date12=$(echo $last_action_date12raw | awk '{print $12}')
last_action12raw=$(echo $page_stripped | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action12=$(echo $last_action12raw | awk '{print $12}')
url12raw=$(echo $page_stripped | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url12=$(echo $url12raw | awk '{print $12}')

echo "$i | $id12 | $title12 | $sponsor12 | $sponsorst12 | $sponsorpar12 | $date12 | $house12 | $senate12 | $enacted12 | $last_action_date12 | $last_action12 | $url12"
echo "$i|$id12|$title12|$sponsor12|$sponsorst12|$sponsorpar12|$date12|$house12|$senate12|$enacted12|$last_action_date12|$last_action12|$url12" >> house-bills.txt

#bill13
bill13raw=$(echo $page_stripped | grep -oP "bill_id.*?(?=\}\,\{)")
bill13=$(echo $bill13raw | awk '{print $13}')
id13raw=$(echo $page_stripped | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id13=$(echo $id13raw | awk '{print $13}')
title13raw=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title13=$(echo $title13raw | awk '{print $13}')
sponsor13raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor13=$(echo $sponsor13raw | awk '{print $13}')
sponsorst13raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst13=$(echo $sponsorst13raw | awk '{print $13}')
sponsorpar13raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar13=$(echo $sponsorpar13raw | awk '{print $13}')
date13raw=$(echo $page_stripped | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date13=$(echo $date13raw | awk '{print $13}')
house13raw=$(echo $page_stripped | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house13=$(echo $house13raw | awk '{print $13}')
senate13raw=$(echo $page_stripped | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate13=$(echo $senate13raw | awk '{print $13}')
enacted13raw=$(echo $page_stripped | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted13=$(echo $enacted13raw | awk '{print $13}')
sponsor13raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor13=$(echo $sponsor13raw | awk '{print $13}')
last_action_date13raw=$(echo $page_stripped | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date13=$(echo $last_action_date13raw | awk '{print $13}')
last_action13raw=$(echo $page_stripped | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action13=$(echo $last_action13raw | awk '{print $13}')
url13raw=$(echo $page_stripped | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url13=$(echo $url13raw | awk '{print $13}')

echo "$i | $id13 | $title13 | $sponsor13 | $sponsorst13 | $sponsorpar13 | $date13 | $house13 | $senate13 | $enacted13 | $last_action_date13 | $last_action13 | $url13"
echo "$i|$id13|$title13|$sponsor13|$sponsorst13|$sponsorpar13|$date13|$house13|$senate13|$enacted13|$last_action_date13|$last_action13|$url13" >> house-bills.txt

#bill14
bill14raw=$(echo $page_stripped | grep -oP "bill_id.*?(?=\}\,\{)")
bill14=$(echo $bill14raw | awk '{print $14}')
id14raw=$(echo $page_stripped | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id14=$(echo $id14raw | awk '{print $14}')
title14raw=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title14=$(echo $title14raw | awk '{print $14}')
sponsor14raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor14=$(echo $sponsor14raw | awk '{print $14}')
sponsorst14raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst14=$(echo $sponsorst14raw | awk '{print $14}')
sponsorpar14raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar14=$(echo $sponsorpar14raw | awk '{print $14}')
date14raw=$(echo $page_stripped | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date14=$(echo $date14raw | awk '{print $14}')
house14raw=$(echo $page_stripped | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house14=$(echo $house14raw | awk '{print $14}')
senate14raw=$(echo $page_stripped | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate14=$(echo $senate14raw | awk '{print $14}')
enacted14raw=$(echo $page_stripped | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted14=$(echo $enacted14raw | awk '{print $14}')
sponsor14raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor14=$(echo $sponsor14raw | awk '{print $14}')
last_action_date14raw=$(echo $page_stripped | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date14=$(echo $last_action_date14raw | awk '{print $14}')
last_action14raw=$(echo $page_stripped | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action14=$(echo $last_action14raw | awk '{print $14}')
url14raw=$(echo $page_stripped | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url14=$(echo $url14raw | awk '{print $14}')

echo "$i | $id14 | $title14 | $sponsor14 | $sponsorst14 | $sponsorpar14 | $date14 | $house14 | $senate14 | $enacted14 | $last_action_date14 | $last_action14 | $url14"
echo "$i|$id14|$title14|$sponsor14|$sponsorst14|$sponsorpar14|$date14|$house14|$senate14|$enacted14|$last_action_date14|$last_action14|$url14" >> house-bills.txt

#bill15
bill15raw=$(echo $page_stripped | grep -oP "bill_id.*?(?=\}\,\{)")
bill15=$(echo $bill15raw | awk '{print $15}')
id15raw=$(echo $page_stripped | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id15=$(echo $id15raw | awk '{print $15}')
title15raw=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title15=$(echo $title15raw | awk '{print $15}')
sponsor15raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor15=$(echo $sponsor15raw | awk '{print $15}')
sponsorst15raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst15=$(echo $sponsorst15raw | awk '{print $15}')
sponsorpar15raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar15=$(echo $sponsorpar15raw | awk '{print $15}')
date15raw=$(echo $page_stripped | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date15=$(echo $date15raw | awk '{print $15}')
house15raw=$(echo $page_stripped | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house15=$(echo $house15raw | awk '{print $15}')
senate15raw=$(echo $page_stripped | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate15=$(echo $senate15raw | awk '{print $15}')
enacted15raw=$(echo $page_stripped | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted15=$(echo $enacted15raw | awk '{print $15}')
sponsor15raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor15=$(echo $sponsor15raw | awk '{print $15}')
last_action_date15raw=$(echo $page_stripped | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date15=$(echo $last_action_date15raw | awk '{print $15}')
last_action15raw=$(echo $page_stripped | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action15=$(echo $last_action15raw | awk '{print $15}')
url15raw=$(echo $page_stripped | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url15=$(echo $url15raw | awk '{print $15}')

echo "$i | $id15 | $title15 | $sponsor15 | $sponsorst15 | $sponsorpar15 | $date15 | $house15 | $senate15 | $enacted15 | $last_action_date15 | $last_action15 | $url15"
echo "$i|$id15|$title15|$sponsor15|$sponsorst15|$sponsorpar15|$date15|$house15|$senate15|$enacted15|$last_action_date15|$last_action15|$url15" >> house-bills.txt

#bill16
bill16raw=$(echo $page_stripped | grep -oP "bill_id.*?(?=\}\,\{)")
bill16=$(echo $bill16raw | awk '{print $16}')
id16raw=$(echo $page_stripped | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id16=$(echo $id16raw | awk '{print $16}')
title16raw=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title16=$(echo $title16raw | awk '{print $16}')
sponsor16raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor16=$(echo $sponsor16raw | awk '{print $16}')
sponsorst16raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst16=$(echo $sponsorst16raw | awk '{print $16}')
sponsorpar16raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar16=$(echo $sponsorpar16raw | awk '{print $16}')
date16raw=$(echo $page_stripped | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date16=$(echo $date16raw | awk '{print $16}')
house16raw=$(echo $page_stripped | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house16=$(echo $house16raw | awk '{print $16}')
senate16raw=$(echo $page_stripped | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate16=$(echo $senate16raw | awk '{print $16}')
enacted16raw=$(echo $page_stripped | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted16=$(echo $enacted16raw | awk '{print $16}')
sponsor16raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor16=$(echo $sponsor16raw | awk '{print $16}')
last_action_date16raw=$(echo $page_stripped | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date16=$(echo $last_action_date16raw | awk '{print $16}')
last_action16raw=$(echo $page_stripped | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action16=$(echo $last_action16raw | awk '{print $16}')
url16raw=$(echo $page_stripped | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url16=$(echo $url16raw | awk '{print $16}')

echo "$i | $id16 | $title16 | $sponsor16 | $sponsorst16 | $sponsorpar16 | $date16 | $house16 | $senate16 | $enacted16 | $last_action_date16 | $last_action16 | $url16"
echo "$i|$id16|$title16|$sponsor16|$sponsorst16|$sponsorpar16|$date16|$house16|$senate16|$enacted16|$last_action_date16|$last_action16|$url16" >> house-bills.txt

#bill17
bill17raw=$(echo $page_stripped | grep -oP "bill_id.*?(?=\}\,\{)")
bill17=$(echo $bill17raw | awk '{print $17}')
id17raw=$(echo $page_stripped | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id17=$(echo $id17raw | awk '{print $17}')
title17raw=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title17=$(echo $title17raw | awk '{print $17}')
sponsor17raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor17=$(echo $sponsor17raw | awk '{print $17}')
sponsorst17raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst17=$(echo $sponsorst17raw | awk '{print $17}')
sponsorpar17raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar17=$(echo $sponsorpar17raw | awk '{print $17}')
date17raw=$(echo $page_stripped | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date17=$(echo $date17raw | awk '{print $17}')
house17raw=$(echo $page_stripped | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house17=$(echo $house17raw | awk '{print $17}')
senate17raw=$(echo $page_stripped | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate17=$(echo $senate17raw | awk '{print $17}')
enacted17raw=$(echo $page_stripped | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted17=$(echo $enacted17raw | awk '{print $17}')
sponsor17raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor17=$(echo $sponsor17raw | awk '{print $17}')
last_action_date17raw=$(echo $page_stripped | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date17=$(echo $last_action_date17raw | awk '{print $17}')
last_action17raw=$(echo $page_stripped | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action17=$(echo $last_action17raw | awk '{print $17}')
url17raw=$(echo $page_stripped | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url17=$(echo $url17raw | awk '{print $17}')

echo "$i | $id17 | $title17 | $sponsor17 | $sponsorst17 | $sponsorpar17 | $date17 | $house17 | $senate17 | $enacted17 | $last_action_date17 | $last_action17 | $url17"
echo "$i|$id17|$title17|$sponsor17|$sponsorst17|$sponsorpar17|$date17|$house17|$senate17|$enacted17|$last_action_date17|$last_action17|$url17" >> house-bills.txt

#bill18
bill18raw=$(echo $page_stripped | grep -oP "bill_id.*?(?=\}\,\{)")
bill18=$(echo $bill18raw | awk '{print $18}')
id18raw=$(echo $page_stripped | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id18=$(echo $id18raw | awk '{print $18}')
title18raw=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title18=$(echo $title18raw | awk '{print $18}')
sponsor18raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor18=$(echo $sponsor18raw | awk '{print $18}')
sponsorst18raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst18=$(echo $sponsorst18raw | awk '{print $18}')
sponsorpar18raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar18=$(echo $sponsorpar18raw | awk '{print $18}')
date18raw=$(echo $page_stripped | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date18=$(echo $date18raw | awk '{print $18}')
house18raw=$(echo $page_stripped | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house18=$(echo $house18raw | awk '{print $18}')
senate18raw=$(echo $page_stripped | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate18=$(echo $senate18raw | awk '{print $18}')
enacted18raw=$(echo $page_stripped | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted18=$(echo $enacted18raw | awk '{print $18}')
sponsor18raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor18=$(echo $sponsor18raw | awk '{print $18}')
urllast_action_date18raw=$(echo $page_stripped | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date18=$(echo $last_action_date18raw | awk '{print $18}')
last_action18raw=$(echo $page_stripped | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action18=$(echo $last_action18raw | awk '{print $18}')
url18raw=$(echo $page_stripped | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url18=$(echo $url18raw | awk '{print $18}')

echo "$i | $id18 | $title18 | $sponsor18 | $sponsorst18 | $sponsorpar18 | $date18 | $house18 | $senate18 | $enacted18 | $last_action_date18 | $last_action18 | $url18"
echo "$i|$id18|$title18|$sponsor18|$sponsorst18|$sponsorpar18|$date18|$house18|$senate18|$enacted18|$last_action_date18|$last_action18|$url18" >> house-bills.txt


#bill19
bill19raw=$(echo $page_stripped | grep -oP "bill_id.*?(?=\}\,\{)")
bill19=$(echo $bill19raw | awk '{print $19}')
id19raw=$(echo $page_stripped | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id19=$(echo $id19raw | awk '{print $19}')
title19raw=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title19=$(echo $title19raw | awk '{print $19}')
sponsor19raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor19=$(echo $sponsor19raw | awk '{print $19}')
sponsorst19raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst19=$(echo $sponsorst19raw | awk '{print $19}')
sponsorpar19raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar19=$(echo $sponsorpar19raw | awk '{print $19}')
date19raw=$(echo $page_stripped | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date19=$(echo $date19raw | awk '{print $19}')
house19raw=$(echo $page_stripped | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house19=$(echo $house19raw | awk '{print $19}')
senate19raw=$(echo $page_stripped | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate19=$(echo $senate19raw | awk '{print $19}')
enacted19raw=$(echo $page_stripped | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted19=$(echo $enacted19raw | awk '{print $19}')
sponsor19raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor19=$(echo $sponsor19raw | awk '{print $19}')
last_action_date19raw=$(echo $page_stripped | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date19=$(echo $last_action_date19raw | awk '{print $19}')
last_action19raw=$(echo $page_stripped | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action19=$(echo $last_action19raw | awk '{print $19}')
url19raw=$(echo $page_stripped | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url19=$(echo $url19raw | awk '{print $19}')

echo "$i | $id19 | $title19 | $sponsor19 | $sponsorst19 | $sponsorpar19 | $date19 | $house19 | $senate19 | $enacted19 | $last_action_date19 | $last_action19 | $url19"
echo "$i|$id19|$title19|$sponsor19|$sponsorst19|$sponsorpar19|$date19|$house19|$senate19|$enacted19|$last_action_date19|$last_action19|$url19" >> house-bills.txt

#bill20
bill20raw=$(echo $page_stripped | grep -oP "bill_id.*?(?=\}\,\{)")
bill20=$(echo $bill20raw | awk '{print $20}')
id20raw=$(echo $page_stripped | grep -oP "(?<=bill\_slug\"\:\").*?(?=\")")
id20=$(echo $id20raw | awk '{print $20}')
title20raw=$(echo $title_list | grep -oP "(?<=short\_title\"\:\_\").*?(?=\")")
title20=$(echo $title20raw | awk '{print $20}')
sponsor20raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor20=$(echo $sponsor20raw | awk '{print $20}')
sponsorst20raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_state\"\:\").*?(?=\")")
sponsorst20=$(echo $sponsorst20raw | awk '{print $20}')
sponsorpar20raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_party\"\:\").*?(?=\")")
sponsorpar20=$(echo $sponsorpar20raw | awk '{print $20}')
date20raw=$(echo $page_stripped | grep -oP "(?<=introduced\_date\"\:\").*?(?=\")")
date20=$(echo $date20raw | awk '{print $20}')
house20raw=$(echo $page_stripped | grep -oP "(?<=house\_passage\"\:\").*?(?=\")")
house20=$(echo $house20raw | awk '{print $20}')
senate20raw=$(echo $page_stripped | grep -oP "(?<=senate\_passage\"\:\").*?(?=\")")
senate20=$(echo $senate20raw | awk '{print $20}')
enacted20raw=$(echo $page_stripped | grep -oP "(?<=enacted\"\:\").*?(?=\")")
enacted20=$(echo $enacted20raw | awk '{print $20}')
sponsor20raw=$(echo $page_stripped | grep -oP "(?<=sponsor\_name\"\:\").*?(?=\")")
sponsor20=$(echo $sponsor20raw | awk '{print $20}')
last_action_date20raw=$(echo $page_stripped | grep -oP "(?<=major\_action\_date\"\:\").*?(?=\")")
last_action_date20=$(echo $last_action_date20raw | awk '{print $20}')
last_action20raw=$(echo $page_stripped | grep -oP "(?<=major\_action\"\:\").*?(?=\")")
last_action20=$(echo $last_action20raw | awk '{print $20}')
url20raw=$(echo $page_stripped | grep -oP "(?<=congressdotgov_url\"\:\").*?(?=\")")
url20=$(echo $url20raw | awk '{print $20}')

echo "$i | $id20 | $title20 | $sponsor20 | $sponsorst20 | $sponsorpar20 | $date20 | $house20 | $senate20 | $enacted20 | $last_action_date20 | $last_action20 | $url20"
echo "$i|$id20|$title20|$sponsor20|$sponsorst20|$sponsorpar20|$date20|$house20|$senate20|$enacted20|$last_action_date20|$last_action20|$url20" >> house-bills.txt

#tester
#echo "$bill1"

#sleep $[ ( $RANDOM % 4 )  + 1 ]s
done
done
